"""
Musical Genre Standardization Dictionary.
Format: 'raw_tag': 'final_genre'
"""

GENRE_DICT = {
    ###############################################################################
    # Pop and derivatives (western)
    ###############################################################################
    'contemporary pop': 'contemporary pop',
    'mainstream pop': 'mainstream pop',
    'vocal pop': 'vocal pop',
    'traditional pop': 'traditional pop',
    'pop tradicional': 'traditional pop',
    'dance pop': 'dance pop',
    'dance-pop': 'dance pop',
    'dancepop': 'dance pop',
    'teen pop': 'teen pop',
    'teen-pop': 'teen pop',
    'teenpop': 'teen pop',
    'power pop': 'power pop',
    'power-pop': 'power pop',
    'powerpop': 'power pop',
    'synth pop': 'synth pop',
    'synth-pop': 'synth pop',
    'synthpop': 'synth pop',
    'electropop': 'electropop',
    'electro pop': 'electropop',
    'bubblegum pop': 'bubblegum pop',
    'bubblegum': 'bubblegum pop',
    'pop rock': 'pop rock',
    'pop-rock': 'pop rock',
    'pop rock español': 'latin pop rock',
    'pop latino': 'latin pop',
    'latin pop': 'latin pop',
    'balada': 'ballad',
    'balada romántica': 'romantic ballad',
    'balada pop': 'pop ballad',
    'singer songwriter': 'singer-songwriter',
    'singer-songwriter': 'singer-songwriter',
    'singer/songwriter': 'singer-songwriter',
    'cantautor': 'singer-songwriter',
    'cantautora': 'singer-songwriter',
    'cantautor pop': 'singer-songwriter',
    'chamber pop': 'chamber pop',
    'chamber-pop': 'chamber pop',
    'chamber': 'chamber pop',
    'orchestral pop': 'orchestral pop',
    'orchestral-pop': 'orchestral pop',
    'symphonic pop': 'orchestral pop',
    'baroque pop': 'baroque pop',
    'baroque-pop': 'baroque pop',
    'sunshine pop': 'sunshine pop',

    ###############################################################################
    # Rock
    ###############################################################################
    'rock and roll': 'rock and roll',
    'rock & roll': 'rock and roll',
    'rock n roll': 'rock and roll',
    'rocanrol': 'rock and roll',
    'rockabilly': 'rockabilly',
    'classic rock': 'classic rock',
    'rock clásico': 'classic rock',
    'hard rock': 'hard rock',
    'hard-rock': 'hard rock',
    'blues rock': 'blues rock',
    'blues-rock': 'blues rock',
    'folk rock': 'folk rock',
    'folk-rock': 'folk rock',
    'garage rock': 'garage rock',
    'garage-rock': 'garage rock',
    'glam rock': 'glam rock',
    'glam-rock': 'glam rock',
    'psychedelic rock': 'psychedelic rock',
    'rock psicodélico': 'psychedelic rock',
    'southern rock': 'southern rock',
    'roots rock': 'roots rock',
    'roots-rock': 'roots rock',
    'swamp rock': 'swamp rock',
    'swamp-rock': 'swamp rock',
    'arena rock': 'arena rock',
    'stadium rock': 'stadium rock',
    'heartland rock': 'heartland rock',
    'rock en español': 'latin rock',
    'rock español': 'latin rock',
    'rock latino': 'latin rock',
    'soft rock': 'soft rock',

    ###############################################################################
    # Alternative Rock/Indie Rock
    ###############################################################################
    'alternative': 'alternative rock',
    'alternativo': 'alternative rock',
    'rock alternativo': 'alternative rock',
    'alternative rock': 'alternative rock',
    'indie': 'indie rock',
    'indie rock': 'indie rock',
    'indie-rock': 'indie rock',
    'indie folk': 'indie folk',
    'britpop': 'britpop',
    'brit pop': 'britpop',
    'brit-pop': 'britpop',
    'grunge': 'grunge',
    'post-grunge': 'post-grunge',
    'post grunge': 'post-grunge',
    'emo': 'emo',
    'emocore': 'emo',
    'emo-core': 'emo',
    'emo-pop': 'emo pop',
    'emo pop': 'emo pop',
    'emopop': 'emo pop',
    'screamo': 'screamo',
    'shoegaze': 'shoegaze',
    'shoegazing': 'shoegaze',
    'uk shoegaze': 'shoegaze',
    'noise pop': 'noise pop',
    'noise-pop': 'noise pop',
    'noisepop': 'noise pop',
    'lo-fi': 'lo-fi',
    'lofi': 'lo-fi',
    'low fidelity': 'lo-fi',
    'post-hardcore': 'post-hardcore',
    'post hardcore': 'post-hardcore',
    'posthardcore': 'post-hardcore',
    'slowcore': 'slowcore',
    'slow core': 'slowcore',
    'sadcore': 'sadcore',
    'sad core': 'sadcore',
    'madchester': 'madchester',
    'baggy': 'baggy',
    'c86': 'c86',
    'uk post-punk revival': 'post-punk revival',

    ###############################################################################
    # Metal
    ###############################################################################
    'heavy metal': 'heavy metal',
    'heavy-metal': 'heavy metal',
    'traditional heavy metal': 'heavy metal',
    'trad heavy metal': 'heavy metal',
    'nwobhm': 'nwobhm',
    'thrash metal': 'thrash metal',
    'thrash-metal': 'thrash metal',
    'thrash': 'thrash metal',
    'death metal': 'death metal',
    'death-metal': 'death metal',
    'death': 'death metal',
    'melodic death metal': 'melodic death metal',
    'melodeath': 'melodic death metal',
    'technical death metal': 'technical death metal',
    'tech death': 'technical death metal',
    'brutal death metal': 'brutal death metal',
    'black metal': 'black metal',
    'black-metal': 'black metal',
    'black': 'black metal',
    'atmospheric black metal': 'atmospheric black metal',
    'symphonic black metal': 'symphonic black metal',
    'depressive black metal': 'depressive black metal',
    'dsbm': 'dsbm',
    'raw black metal': 'raw black metal',
    'power metal': 'power metal',
    'power-metal': 'power metal',
    'power': 'power metal',
    'epic power metal': 'power metal',
    'symphonic power metal': 'symphonic power metal',
    'nu metal': 'nu metal',
    'nu-metal': 'nu metal',
    'nü-metal': 'nu metal',
    'metalcore': 'metalcore',
    'metal core': 'metalcore',
    'melodic metalcore': 'melodic metalcore',
    'deathcore': 'deathcore',
    'death core': 'deathcore',
    'doom metal': 'doom metal',
    'doom-metal': 'doom metal',
    'doom': 'doom metal',
    'epic doom': 'doom metal',
    'funeral doom': 'funeral doom',
    'death-doom': 'death-doom',
    'death doom': 'death-doom',
    'gothic metal': 'gothic metal',
    'gothic-metal': 'gothic metal',
    'goth metal': 'gothic metal',
    'symphonic metal': 'symphonic metal',
    'symphonic-metal': 'symphonic metal',
    'symphonic': 'symphonic metal',
    'folk metal': 'folk metal',
    'folk-metal': 'folk metal',
    'pagan metal': 'pagan metal',
    'viking metal': 'viking metal',
    'viking-metal': 'viking metal',
    'celtic metal': 'celtic metal',
    'medieval metal': 'medieval metal',
    'nordic folk metal': 'folk metal',
    'eastern european folk metal': 'folk metal',
    'hurdy gurdy metal': 'hurdy gurdy metal',
    'bagpipe metal': 'bagpipe metal',
    'groove metal': 'groove metal',
    'groove-metal': 'groove metal',
    'post-thrash': 'post-thrash',
    'industrial metal': 'industrial metal',
    'industrial-metal': 'industrial metal',
    'alternative metal': 'alternative metal',
    'alt-metal': 'alternative metal',
    'glam metal': 'glam metal',
    'glam-metal': 'glam metal',
    'hair metal': 'glam metal',
    'pop metal': 'glam metal',
    'hair rock': 'glam metal',
    'speed metal': 'speed metal',
    'speed-metal': 'speed metal',
    'crossover thrash': 'crossover thrash',
    'grindcore': 'grindcore',
    'grind': 'grindcore',
    'goregrind': 'goregrind',
    'pornogrind': 'pornogrind',
    'rap metal': 'rap metal',
    'rap-metal': 'rap metal',
    'rapcore': 'rapcore',

    ###############################################################################
    # Punk
    ###############################################################################
    'punk': 'punk rock',
    'punk rock': 'punk rock',
    'punk-rock': 'punk rock',
    'hardcore punk': 'hardcore punk',
    'hardcore-punk': 'hardcore punk',
    'hardcore': 'hardcore punk',
    'pop punk': 'pop punk',
    'pop-punk': 'pop punk',
    'punk pop': 'pop punk',
    'punk-pop': 'pop punk',
    'happy punk': 'pop punk',
    'happy-punk': 'pop punk',
    'ska punk': 'ska punk',
    'ska-punk': 'ska punk',
    'celtic punk': 'celtic punk',
    'folk punk': 'folk punk',
    'anarcho-punk': 'anarcho-punk',
    'anarchopunk': 'anarcho-punk',
    'crust punk': 'crust punk',
    'crust': 'crust punk',
    'd-beat': 'd-beat',
    'dbeat': 'd-beat',
    'street punk': 'street punk',
    'streetpunk': 'street punk',
    'horror punk': 'horror punk',
    'garage punk': 'garage punk',
    'garage-punk': 'garage punk',
    'cowpunk': 'cowpunk',
    'cow punk': 'cowpunk',
    'deathrock': 'deathrock',
    'death rock': 'deathrock',
    'psychobilly': 'psychobilly',
    'punk blues': 'punk blues',
    'riot grrrl': 'riot grrrl',
    'queercore': 'queercore',
    'taqwacore': 'taqwacore',
    'gypsy punk': 'gypsy punk',

    ###############################################################################
    # Post-Punk / New Wave
    ###############################################################################
    'post-punk': 'post-punk',
    'post punk': 'post-punk',
    'postpunk': 'post-punk',
    'new wave': 'new wave',
    'nueva ola': 'new wave',
    'gothic rock': 'gothic rock',
    'gothic-rock': 'gothic rock',
    'rock gótico': 'gothic rock',
    'darkwave': 'darkwave',
    'dark wave': 'darkwave',
    'coldwave': 'coldwave',
    'cold wave': 'coldwave',
    'ethereal wave': 'ethereal wave',
    'ethereal': 'ethereal wave',
    'minimal wave': 'minimal wave',
    'synthwave': 'synthwave',
    'synth wave': 'synthwave',
    'electroclash': 'electroclash',
    'dance-punk': 'dance-punk',
    'dance punk': 'dance-punk',
    'no wave': 'no wave',
    'nowave': 'no wave',
    'yacht rock': 'yacht rock',
    'post-punk revival': 'post-punk revival',
    'new wave revival': 'new wave revival',
    'indie sleaze': 'indie sleaze',

    ###############################################################################
    # Experimental / Prog Rock / Art Rock
    ###############################################################################
    'progressive': 'progressive rock',
    'prog': 'progressive rock',
    'prog rock': 'progressive rock',
    'prog-rock': 'progressive rock',
    'progressive rock': 'progressive rock',
    'rock progresivo': 'progressive rock',
    'prog metal': 'progressive metal',
    'prog-metal': 'progressive metal',
    'progressive metal': 'progressive metal',
    'metal progresivo': 'progressive metal',
    'art rock': 'art rock',
    'art-rock': 'art rock',
    'art pop': 'art pop',
    'art-pop': 'art pop',
    'artpop': 'art pop',
    'avant-garde': 'avant-garde',
    'vanguardia': 'avant-garde',
    'avant prog': 'avant prog',
    'avant-prog': 'avant prog',
    'avant pop': 'avant pop',
    'avant-pop': 'avant pop',
    'experimental': 'experimental',
    'experimental pop': 'experimental pop',
    'pop psicodélico': 'psychedelic pop',
    'psychedelic pop': 'psychedelic pop',
    'post-rock': 'post-rock',
    'post rock': 'post-rock',
    'postrock': 'post-rock',
    'math rock': 'math rock',
    'math-rock': 'math rock',
    'mathrock': 'math rock',
    'mathcore': 'mathcore',
    'math core': 'mathcore',
    'djent': 'djent',
    'progressive post-hardcore': 'progressive post-hardcore',
    'progressive post hardcore': 'progressive post-hardcore',
    'progressive posthardcore': 'progressive post-hardcore',
    'prog post-hardcore': 'progressive post-hardcore',
    'prog post hardcore': 'progressive post-hardcore',
    'prog posthardcore': 'progressive post-hardcore',
    'progcore': 'progressive post-hardcore',
    'swancore': 'swancore',
    'swan-core': 'swancore',
    'Progressive Metalcore': 'Progressive Metalcore',
    'Prog Metalcore': 'Progressive Metalcore',
    'krautrock': 'krautrock',
    'symphonic rock': 'symphonic rock',
    'rock sinfónico': 'symphonic rock',
    'space rock': 'space rock',
    'space-rock': 'space rock',
    'canterbury': 'canterbury scene',
    'canterbury scene': 'canterbury scene',
    'rio': 'rock in opposition',
    'rock in opposition': 'rock in opposition',
    'zeuhl': 'zeuhl',
    'musique concrete': 'musique concrète',
    'música concreta': 'musique concrète',
    'electroacoustic': 'electroacoustic',
    'electroacústica': 'electroacoustic',
    'noise': 'noise',
    'noise music': 'noise',
    'noise rock': 'noise rock',
    'drone': 'drone',
    'drone music': 'drone',
    'experimental electronic': 'experimental electronic',
    'electrónica experimental': 'experimental electronic',
    'glitch': 'glitch',
    'glitch music': 'glitch',
    'idm': 'idm',
    'braindance': 'braindance',
    'minimalism': 'minimalism',
    'minimalismo': 'minimalism',
    'minimal music': 'minimalism',

    ###############################################################################
    # Hip-Hop/Rap/Trap
    ###############################################################################
    'hip hop': 'hip hop',
    'hip-hop': 'hip hop',
    'hiphop': 'hip hop',
    'rap': 'rap',
    'trap': 'trap',
    'trap anglo': 'trap',
    'cloud rap': 'cloud rap',
    'mumble rap': 'mumble rap',
    'drill': 'drill',
    'uk drill': 'drill',
    'chicago drill': 'drill',
    'brooklyn drill': 'drill',
    'gangsta rap': 'gangsta rap',
    'g-funk': 'g-funk',
    'gfunk': 'g-funk',
    'conscious rap': 'conscious rap',
    'rap conciencia': 'conscious rap',
    'political hip-hop': 'political hip-hop',
    'political rap': 'political hip-hop',
    'east coast': 'east coast hip-hop',
    'east coast hip hop': 'east coast hip-hop',
    'west coast': 'west coast hip-hop',
    'west coast hip hop': 'west coast hip-hop',
    'southern rap': 'southern hip-hop',
    'dirty south': 'southern hip-hop',
    'southern hip hop': 'southern hip-hop',
    'old school rap': 'old school hip-hop',
    'old school hip hop': 'old school hip-hop',
    'rap rock': 'rap rock',
    'rap-rock': 'rap rock',
    'alternative hip hop': 'alternative hip hop',
    'hip hop alternativo': 'alternative hip hop',
    'jazz rap': 'jazz rap',
    'jazz-rap': 'jazz rap',
    'horrorcore': 'horrorcore',
    'boom bap': 'boom bap',
    'boombap': 'boom bap',
    'hardcore hip hop': 'hardcore hip hop',
    'turntablism': 'turntablism',
    'instrumental hip hop': 'instrumental hip hop',
    'crunk': 'crunk',
    'snap music': 'snap',
    'snap': 'snap',
    'hyphy': 'hyphy',
    'chopped and screwed': 'chopped and screwed',
    'screwed': 'chopped and screwed',
    'emo rap': 'emo rap',
    'emrap': 'emo rap',
    'soundcloud rap': 'soundcloud rap',
    'uk hip hop': 'uk hip hop',
    'british hip hop': 'uk hip hop',
    'grime': 'grime',
    'abstract hip hop': 'abstract hip hop',
    'christian hip hop': 'christian hip hop',
    'gospel rap': 'gospel rap',
    'nerdcore': 'nerdcore',
    'comedy rap': 'comedy rap',
    'freestyle': 'freestyle',
    'freestyle rap': 'freestyle',
    'battle rap': 'battle rap',

    ###############################################################################
    # Electronic/Dance
    ###############################################################################
    'electronic': 'electronic',
    'electrónica': 'electronic',
    'electronica': 'electronic',
    'dance': 'dance',
    'edm': 'edm',
    'música electrónica': 'electronic',
    'house': 'house',
    'deep house': 'deep house',
    'progressive house': 'progressive house',
    'tech house': 'tech house',
    'tropical house': 'tropical house',
    'electro house': 'electro house',
    'future house': 'future house',
    'garage house': 'garage house',
    'chicago house': 'chicago house',
    'french house': 'french house',
    'italo house': 'italo house',
    'latin house': 'latin house',
    'techno': 'techno',
    'detroit techno': 'detroit techno',
    'minimal techno': 'minimal techno',
    'industrial techno': 'industrial techno',
    'acid techno': 'acid techno',
    'trance': 'trance',
    'psytrance': 'psytrance',
    'progressive trance': 'progressive trance',
    'uplifting trance': 'uplifting trance',
    'vocal trance': 'vocal trance',
    'goa trance': 'goa trance',
    'dubstep': 'dubstep',
    'brostep': 'brostep',
    'future bass': 'future bass',
    'trap edm': 'trap edm',
    'drum and bass': 'drum and bass',
    'drum & bass': 'drum and bass',
    'dnb': 'dnb',
    'liquid drum and bass': 'liquid drum and bass',
    'jungle': 'jungle',
    'neurofunk': 'neurofunk',
    'ambient': 'ambient',
    'chillout': 'chillout',
    'chill': 'chill',
    'downtempo': 'downtempo',
    'lounge': 'lounge',
    'vaporwave': 'vaporwave',
    'chillwave': 'chillwave',
    'retrowave': 'retrowave',
    'dreamwave': 'dreamwave',
    'electro': 'electro',
    'big room': 'big room',
    'bigroom': 'bigroom',
    'festival trap': 'festival trap',
    'mainstage': 'mainstage',
    'hardstyle': 'hardstyle',
    'hardcore techno': 'hardcore techno',
    'gabber': 'gabber',
    'hard trance': 'hard trance',
    'jumpstyle': 'jumpstyle',
    'uk garage': 'uk garage',
    'garage': 'garage',
    '2-step': '2-step',
    'bassline': 'bassline',
    'disco': 'disco',
    'nu-disco': 'nu-disco',
    'italo disco': 'italo disco',
    'space disco': 'space disco',
    'acid house': 'acid house',
    'acid': 'acid',
    'rave': 'rave',
    'old school rave': 'old school rave',
    'schranz': 'schranz',
    'hard techno': 'hard techno',
    'mainstream hardcore': 'mainstream hardcore',
    'industrial hardcore': 'industrial hardcore',
    'frenchcore': 'frenchcore',
    'german hardcore': 'german hardcore',
    'berlin techno': 'berlin techno',
    'rotterdam techno': 'rotterdam techno',
    'eurodance': 'eurodance',
    'euro house': 'euro house',
    'euro techno': 'euro techno',
    'german eurodance': 'eurodance',
    'italo dance': 'italo dance',
    'swedish eurodance': 'eurodance',
    'dutch eurodance': 'eurodance',
    'europop': 'europop',
    'scandinavian pop': 'scandinavian pop',
    'phonk': 'phonk',

    ###############################################################################
    # R&B / Soul / Funk
    ###############################################################################
    'rnb': 'rhythm and blues',
    'r&b': 'rhythm and blues',
    'r and b': 'rhythm and blues',
    'rhythm and blues': 'rhythm and blues',
    'rhythm & blues': 'rhythm and blues',
    'funk': 'funk',
    'funk music': 'funk',
    'p-funk': 'p-funk',
    'funk rock': 'funk rock',
    'soul': 'soul',
    'soul music': 'soul',
    'soul clásico': 'soul',
    'classic soul': 'soul',
    'contemporary r&b': 'contemporary r&b',
    'contemporary rnb': 'contemporary r&b',
    'r&b contemporáneo': 'contemporary r&b',
    'neo soul': 'neo soul',
    'neo-soul': 'neo soul',
    'neosoul': 'neo soul',
    'alternative r&b': 'alternative r&b',
    'alternative rnb': 'alternative r&b',
    'alt r&b': 'alternative r&b',
    'r&b alternativo': 'alternative r&b',
    'pbr&b': 'pbr&b',
    'quiet storm': 'quiet storm',
    'new jack swing': 'new jack swing',
    'new jack': 'new jack swing',
    'jack swing': 'new jack swing',
    'funk soul': 'funk soul',
    'soul funk': 'funk soul',
    'psychedelic soul': 'psychedelic soul',
    'soul psicodélico': 'psychedelic soul',
    'blue eyed soul': 'blue-eyed soul',
    'blue-eyed soul': 'blue-eyed soul',
    'trap soul': 'trap soul',
    'trap r&b': 'trap soul',
    'r&b latino': 'latin r&b',
    'latin r&b': 'latin r&b',
    'rnb latino': 'latin r&b',
    'northern soul': 'northern soul',
    'southern soul': 'southern soul',
    'motown': 'motown',
    'motown soul': 'motown',
    'motown sound': 'motown',
    'philly soul': 'philly soul',
    'philadelphia soul': 'philly soul',
    'chicago soul': 'chicago soul',
    'memphis soul': 'memphis soul',
    'deep soul': 'deep soul',
    'gospel soul': 'gospel soul',
    'smooth soul': 'smooth soul',
    'urban contemporary': 'urban contemporary',
    'urban r&b': 'urban contemporary',
    'slow jam': 'slow jam',
    'slow jams': 'slow jam',

    ###############################################################################
    # Jazz / Blues
    ###############################################################################
    'jazz': 'jazz',
    'jazz music': 'jazz',
    'trad jazz': 'traditional jazz',
    'traditional jazz': 'traditional jazz',
    'dixieland': 'dixieland',
    'new orleans jazz': 'new orleans jazz',
    'swing': 'swing',
    'big band': 'big band',
    'bigband': 'big band',
    'bebop': 'bebop',
    'bop': 'bebop',
    'cool jazz': 'cool jazz',
    'west coast jazz': 'cool jazz',
    'hard bop': 'hard bop',
    'free jazz': 'free jazz',
    'avant-garde jazz': 'avant-garde jazz',
    'smooth jazz': 'smooth jazz',
    'acid jazz': 'acid jazz',
    'soul jazz': 'soul jazz',
    'blues': 'blues',
    'blues music': 'blues',
    'delta blues': 'delta blues',
    'chicago blues': 'chicago blues',
    'electric blues': 'electric blues',
    'rhythm and blues clasico': 'classic rhythm and blues',
    'r&b clasico': 'classic rhythm and blues',
    'classic r&b': 'classic rhythm and blues',
    'piedmont blues': 'piedmont blues',
    'texas blues': 'texas blues',
    'memphis blues': 'memphis blues',
    'swamp blues': 'swamp blues',
    'british blues': 'british blues',
    'country blues': 'country blues',

    ###############################################################################
    # Folk / Roots
    ###############################################################################
    'folklore': 'folk',
    'folk': 'folk',
    'folk music': 'folk',
    'traditional folk': 'traditional folk',
    'folk tradicional': 'traditional folk',
    'country folk': 'country folk',
    'celtic': 'celtic folk',
    'celtic folk': 'celtic folk',
    'música celta': 'celtic folk',
    'irish folk': 'irish folk',
    'scottish folk': 'scottish folk',
    'sean nós': 'sean nós',
    'ceilidh': 'ceilidh',
    'breton music': 'breton music',
    'musique bretonne': 'breton music',
    'música galega': 'galician folk',
    'galician folk': 'galician folk',
    'celtic rock': 'celtic rock',
    'fado': 'fado',
    'fado de coimbra': 'fado',
    'fado de lisboa': 'fado',
    'fado vadio': 'fado',
    'fado fusion': 'fado',
    'nueva canción': 'nueva canción',
    'nova cançó': 'nova cançó',
    'cantautor catalán': 'catalan singer-songwriter',
    'cantautor gallego': 'galician singer-songwriter',
    'cantautor andaluz': 'andalusian singer-songwriter',
    'nueva canción rock': 'nueva canción rock',
    'nordic folk': 'nordic folk',
    'scandinavian folk': 'nordic folk',
    'world music': 'world music',
    'música del mundo': 'world music',
    'andina': 'andean music',
    'música andina': 'andean music',
    'andean music': 'andean music',
    'folklore latinoamericano': 'latin american folk',
    'zamacueca': 'zamacueca',
    'cueca': 'cueca',
    'tonada': 'tonada',
    'milonga': 'milonga',
    'zamba': 'zamba',
    'chacarera': 'chacarera',
    'nueva trova': 'nueva trova',
    'cantautor folk': 'folk singer-songwriter',
    'trova': 'trova',
    'contemporary folk': 'contemporary folk',
    'folk contemporáneo': 'contemporary folk',
    'freak folk': 'freak folk',

    ###############################################################################
    # Country
    ###############################################################################
    'country': 'country',
    'country music': 'country',
    'música country': 'country',
    'classic country': 'classic country',
    'country clásico': 'classic country',
    'honky tonk': 'honky tonk',
    'country pop': 'country pop',
    'country-pop': 'country pop',
    'country rock': 'country rock',
    'country-rock': 'country rock',
    'outlaw country': 'outlaw country',
    'bluegrass': 'bluegrass',
    'bluegrass music': 'bluegrass',
    'americana': 'americana',
    'western': 'western',
    'western music': 'western',
    'cowboy': 'cowboy',
    'nashville sound': 'nashville sound',
    'nashville country': 'nashville sound',
    'alternative country': 'alternative country',
    'alt-country': 'alternative country',
    'country alternativo': 'alternative country',
    'insurgent country': 'alternative country',
    'texas country': 'texas country',
    'red dirt': 'red dirt',
    'bakersfield sound': 'bakersfield sound',
    'progressive bluegrass': 'progressive bluegrass',
    'newgrass': 'newgrass',
    'country gospel': 'country gospel',

    ###############################################################################
    # Classical / Academic Music
    ###############################################################################
    'classical': 'classical music',
    'classical music': 'classical music',
    'música clásica': 'classical music',
    'musica clasica': 'classical music',
    'academic music': 'classical music',
    'música académica': 'classical music',
    'symphonic': 'symphonic',
    'symphony': 'symphonic',
    'orchestral': 'orchestral',
    'sinfónica': 'symphonic',
    'orquestal': 'orchestral',
    'opera': 'opera',
    'ópera': 'opera',
    'operatic': 'opera',
    'chamber music': 'chamber music',
    'música de cámara': 'chamber music',
    'baroque': 'baroque',
    'barroco': 'baroque',
    'classicism': 'classicism',
    'clasicismo': 'classicism',
    'romanticism': 'romanticism',
    'romanticismo': 'romanticism',
    'contemporary classical': 'contemporary classical',
    'modern classical': 'modern classical',
    'clásica contemporánea': 'contemporary classical',
    'clásica moderna': 'modern classical',
    'choral': 'choral',
    'vocal classical': 'choral',
    'coral': 'choral',
    'música coral': 'choral',
    'zarzuela': 'zarzuela',
    'operetta': 'operetta',
    'opereta': 'operetta',
    'classical period': 'classical period',
    'early music': 'early music',
    'renaissance music': 'renaissance music',
    'medieval music': 'medieval music',
}

# Generics to discard (not saved)
GENERIC_TAGS = {
    'pop', 'rock', 'metal', 'alternative', 'folk',
    'country', 'blues', 'jazz', 'soul', 'funk', 'rap', 'hip hop',
    'electronic', 'dance', 'classical', 'music', 'instrumental',
    'world', 'latin', 'rnb', 'r&b', 'soundtrack',
    'indie', 'progressive', 'experimental', 'psychedelic',
    'symphonic', 'orchestral', 'chamber', 'vocal'
}
